### PR TITLE
Add env variable to permit running behind SSL-terminating reverse proxy

### PR DESCRIPTION
**Pull request by funkypenguin**
When trying to run Collabora behind an SSL-terminating reverse proxy (I used Traefik), it's necessary (and supported) to set "termination" to true, for the following:

```
Connection via proxy where loolwsd acts as working via https, but actually uses http
```

This was not possible using the current image, so I submit this patch which would allow user to pass "termination=true" environment variable (I used lower-case variable name to remain consistent with existing variables) so that this value is correctly set in loolwsd.xml

### CODE REVIEW

**Comment by timar** [comment]
I believe, termination setting can be passed via extra_params environment variable as well. In fact, all configuration items can be passed that way, but I kept the old ones for backward compatibility. See https://github.com/CollaboraOnline/Docker-CODE/commit/ecf7c29d4596243e87635992da3c4aa0c2f2f65b

**Comment by funkypenguin** [comment]
This'd be ideal - but I think I'm driving it wrong.

I passed this in an env_file:

```
extra_params=--o:ssl.termination=true
```

But when I exec into the container and ```cat /etc/loolwsd/loolwsd.xml```, I still see:

```
<termination desc="Connection via proxy where loolwsd acts as working via https, but actually uses http." type="bool" default="true">false</termination>
```
Where would I expect to see the results of extra_params applied?

Thanks!
D

**Comment by timar** [comment]
It is applied to the command, that starts loolwsd. Command line parameters take precedence over the config file. See: https://github.com/CollaboraOnline/Docker-CODE/blob/334731d9e5127cf03236026d2ca6dbc1e1fef406/scripts/start-libreoffice.sh#L42

**Comment by funkypenguin** [comment]
Understood, thank you. Turns out I was responding to a different error (https://github.com/CollaboraOnline/Docker-CODE/issues/49#issuecomment-447573972)

On the subject of extra_params, how should I pass additions to storage.wopi.host and net.post_allow.host, when these additions include regexs?

**Pull request closed without merging**
